export const messages = {
  staleWarning: 'There have been no non-bot replies for {{afterDays}} days. This {{kind}} will be closed after {{deadline}} unless someone replies or a maintainer applies {{keepOpenLabel}}. Label edits, commits and reactions do not reset this timer.',
  staleClosed: 'Closed automatically after the inactivity warning. This does not mean the report was fixed or rejected on its merits.\n\nTo reopen, reply explaining why it still needs attention and include **{{phrase}}**. This route applies only to this automated timeout, not a later maintainer closure.',
  staleClosedManual: 'Closed automatically after the inactivity warning. This is not a declaration that the report was fixed. Automatic reopening is unavailable for this episode; a maintainer must reopen it.',
  responseClosedManual: 'Closed automatically because the request in {{requestUrl}} remained unanswered. Automatic reopening is unavailable for this episode following maintainer intervention or the adopted reopening policy; a maintainer must reopen it.',
  responseRequest: 'An essential response is requested from @{{receiver}} in {{requestUrl}}. The separate response timer starts from that request. A reply stops the no-response consequence; it does not prove the information is sufficient.',
  responseWarning: '@{{receiver}}, the request in {{requestUrl}} still needs your response. This {{kind}} will be closed after {{deadline}} without a reply. Other people’s replies renew general activity but do not answer this request.',
  responseClosed: 'Closed automatically because the request in {{requestUrl}} did not receive a reply before the warning deadline.\n\nTo reopen, provide the requested details or explain why it still needs attention and include **{{phrase}}**. Anyone affected may use this route. Reopening returns it to triage, not approval or a declaration that the question was answered.',
  reopened: 'Reopened following an explicit **{{phrase}}** request. This returns the {{kind}} to triage; it does not approve implementation or declare missing information complete.',
  responseReceived: 'A reply to the response request has arrived. The no-response timer has stopped; the requested information still needs ordinary triage.',
  awaitingRelease: 'The change addressing this issue has been merged into **{{branch}}** in {{prUrl}} and is available there to use and test. It is not in stable **{{main}}** yet.\n\nTo try it: {{tryNextUrl}}. Please report whether it resolves the original problem.',
  fixedMain: 'The change addressing this issue is now included in stable **{{main}}** source: {{commitUrl}} ({{prUrl}}). This issue is closed as fixed in that source.\n\nA packaged release, deployment, or app/extension-store update may follow later. This message does not claim that every distribution channel already contains the change.',
  closeAborted: 'The automatic closure was cancelled because the current discussion or policy changed before the close could be applied.'
};
